openapi: 3.0.3
info:
  title: Enterprise Analytics Request Result REST API
  version: '2.2'
  description: |
    This API enables you to retrieve or discard the result of an asynchronous request.

servers:
  - url: '{scheme}://{host}:{port}'
    description: The URL scheme, host, and port are as follows.
    variables:
      scheme:
        default: http
        description: |-
          The URL scheme.
          Use `https` for secure access.
        enum:
          - http
          - https
      host:
        default: localhost
        description: The host name or IP address of a node.
      port:
        default: "8095"
        description: |-
          The Enterprise Analytics Service REST port.
          Use `18095` for secure access.
        enum:
          - "8095"
          - "18095"

paths:
  /api/v1/request/result/{request_id}/{job_id}:
    get:
      operationId: get_request_result
      summary: Retrieve Request Result
      description: >
        Enables you to retrieve the result of a request that was executed in `async` mode.
      parameters:
        - $ref: "#/components/parameters/RequestId"
        - $ref: "#/components/parameters/JobId"
      security:
        - AnalyticsManageAnalyticsAccess: []
      responses:
        "200":
          $ref: '#/components/responses/OK'
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
    delete:
      operationId: delete_request_result
      summary: Discard Request Result
      description: >
        Enables you to discard the result of a request that was executed in `async` mode.
      parameters:
        - $ref: "#/components/parameters/RequestId"
        - $ref: "#/components/parameters/JobId"
      security:
        - AnalyticsManageAnalyticsAccess: []
      responses:
        "202":
          $ref: '#/components/responses/Deleted'
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'

components:

  parameters:
    RequestId:
      name: request_id
      in: path
      required: true
      description: The unique identifier of the request.
      schema:
        type: string
        format: UUID
    JobId:
      name: job_id
      in: path
      required: true
      description: The identifier of the job associated with the request.
      schema:
        type: string

  schemas:
    ResultResponse:
      title: Result Response
      type: object
      properties:
        results:
          type: array
          description: >
            An array of all the objects returned by the query.
            An object can be any JSON value.
          items:
            type: object
        metrics:
          allOf:
            - $ref: "request.yaml#/components/schemas/ResponsesCommonYardsticks"
            - $ref: "request.yaml#/components/schemas/ResponsesLocalYardsticks"
        profile:
          type: object
          description: An object containing the query profile, if requested.
        createdAt:
          type: string
          format: date-time
          description: The timestamp when the request was created.

  responses:
    OK:
      description: The operation was successful.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResultResponse"

    Deleted:
      description: The operation was accepted.

    BadRequest:
      description: >
        Bad request.
        The request is invalid, for example the request ID or job ID is missing or their format is invalid.

    Unauthorized:
      description: >
        Unauthorized.
        The user name or password may be incorrect.

    NotFound:
      description: >
        Not found.
        The specified request ID or job ID does not exist, or the result has expired.

  securitySchemes:
    AnalyticsManageAnalyticsAccess:
      type: http
      scheme: basic
      description: |-
        Users must have one of the following RBAC roles:

        * Full Admin
        * Cluster Admin
        * Enterprise Analytics Admin
        * Enterprise Analytics Access

