/*
Copyright 2017-Present Couchbase, Inc.

Use of this software is governed by the Business Source License included in
the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
file, in accordance with the Business Source License, use of this software will
be governed by the Apache License, Version 2.0, included in the file
licenses/APL2.txt.
*/

import angular from "angular";

export default 'cwConstantsService';

angular
  .module('cwConstantsService', [])
  .factory('cwConstantsService', getCwConstantsService);



//
// the cwConstantsService contains a number of constants used by the query workbench, such as
// queries, URL prefixes, etc. This version is defined for the regular query workbench inside
// the Couchbase admin UI, a different version will be defined for CBAS, and for the stand-alone
// version
//



function getCwConstantsService() {

  var cwConstantsService = {};

  // do we automatically run queries if the user clicks enter after a semicolon?
  cwConstantsService.autoExecuteQueryOnEnter = true;

  // don't allow multiple queries to run at once
  cwConstantsService.forbidMultipleQueries = false;

  // URL to use for running queries
  cwConstantsService.queryURL = "../_p/cbas/query/service";

  // URL to use to cancel running queries
  cwConstantsService.canelQueryURL = "../_p/cbas/analytics/admin/active_requests";

  // URL to use to get the bucket connection state
  cwConstantsService.bucketStateURL = "../_p/cbas/analytics/buckets";

  // URL to get user visible buckets
  cwConstantsService.clusterBucketsURL = "../pools/default/buckets";

  // URL to use to get the analytics stats
  // TODO switch back to ../_p/cbas/analytics/status/ingestion
  cwConstantsService.analyticsStatsURL = "../_p/cbas/analytics/status/ingestion/v2";

  // URL to use to get AWS supported regions
  cwConstantsService.awsRegionsURL = "../_p/cbas/analytics/link/enum/s3/region";

  // should we get passwords from the Couchbase server?
  cwConstantsService.getCouchbaseBucketPasswords = false;

  // should we run 'explain' in the background for each query?
  cwConstantsService.autoExplain = false;

  // should we show the bucket analysis pane at all?
  cwConstantsService.showBucketAnalysis = true;

  // allow a suffix to the key used for local storage
  cwConstantsService.localStorageSuffix = "cbas";

  // query language mode for ACE editor
  cwConstantsService.queryMode = 'sql-plus-plus';

  // should queries include an array of credentials? ("creds")
  cwConstantsService.sendCreds = false;

  // query id parameter name (for query cancellation)
  cwConstantsService.queryIdParam = "client_context_id";

  // the following query asks Couchbase for a list of keyspaces, returning the 'id',
  // and a 'has_prim' boolean indicating whether or not it has a primary index, and
  // 'has_sec' indicating secondary indexes. For a different system, just make sure
  // the returned schema has 'id' and 'has_prim'.
  cwConstantsService.keyspaceQuery =`
SELECT meta.*
FROM (
  SELECT ds.DatabaseName,
  ds.DataverseName,
ds.DataverseName || '.' || ds.DatasetName AS datasetFullyQualifiedName,
  ds.DatasetName AS id,
  TRUE AS isDataset,
  ds.BucketName AS bucketName,
  ds.ScopeName AS scopeName,
  ds.CollectionName AS collectionName,
  ds.BucketDataverseName AS linkDataverseName,
  ds.BucketDatabaseName AS linkDatabaseName,
  ds.LinkDataverseName AS linkDataverseName2,
  ds.LinkDatabaseName AS linkDatabaseName2,
  ds.\`Filter\` AS \`filter\`,
  ds.LinkName,
  ds.DatasetType,
  ds.DatatypeName,
  ds.InternalDetails.PrimaryKey as primaryKey,
  ds.InternalDetails.PrimaryKeyTypes as primaryKeyTypes,
  ds.InternalDetails.\`Autogenerated\` as primaryKeyAutogenerated,
  ds.ViewDetails,
  t.Derived.Record.Fields AS ViewFields,
  concat2(', ', (
    SELECT VALUE FieldName || ' ' || ( CASE WHEN LOWER(FieldType) = 'int64' THEN 'BIGINT' ELSE UPPER(FieldType) END) || ( CASE WHEN NOT IsNullable
AND NOT IsMissable THEN ' NOT UNKNOWN' ELSE '' END)
FROM t.Derived.Record.Fields)) AS TypeString,
  (
    SELECT idx.IndexName,
  idx.SearchKey,
  idx.SearchKeyElements,
  idx.SearchKeyType
FROM Metadata.\`Index\` AS idx
WHERE idx.IsPrimary = FALSE
AND idx.DatabaseName = ds.DatabaseName
AND idx.DatasetName = ds.DatasetName
AND idx.DataverseName = ds.DataverseName) AS indexes,
  ds.ExternalDetails.Properties AS externalDetails
FROM Metadata.\`Dataset\` AS ds LEFT
JOIN Metadata.Datatype t ON ds.DatabaseName = t.DatabaseName AND ds.DataverseName = t.DataverseName
AND t.DatatypeName = ds.DatatypeName
WHERE (ds.DataverseName != 'Metadata'
)
UNION ALL
SELECT dv.DatabaseName,
  dv.DataverseName,
  TRUE AS isDataverse,
  (
    SELECT l.Name
FROM Metadata.\`Link\` AS l
WHERE l.DatabaseName = dv.DatabaseName AND l.DataverseName = dv.DataverseName) AS links
FROM Metadata.\`Dataverse\` AS dv
WHERE dv.DataverseName != 'Metadata'

  UNION ALL
SELECT db.DatabaseName,
  TRUE AS isDatabase
FROM Metadata.\`Database\` AS db
WHERE db.DatabaseName != 'System'

  UNION ALL
SELECT DatabaseName,
  DataverseName,
  Name,
  IsActive,
  ClusterName,
  \`Type\` AS LinkType,
  TRUE AS isLink
FROM Metadata.\`Link\`) meta
ORDER BY
  meta.isDatabase DESC,
  meta.isDataverse DESC,
  meta.isLink DESC,
  meta.DatabaseName,
  meta.DataverseName,
  meta.LinkName,
  meta.id;`; // make sure dataverses first, then links, then datasets

  // should we permit schema inquiries in the bucket analysis pane?
  cwConstantsService.showSchemas = false;

  // labels for different types of buckets in the analysis pane
  cwConstantsService.analysisFirstSection = "Datasets";
  cwConstantsService.analysisSecondSection = "Cluster Buckets";

  // list of trigger queries to update the bucket insights after
  cwConstantsService.bucketInsightsUpdateTriggers = ["CREATE DATAVERSE", "DROP DATAVERSE", "CONNECT LINK", "DISCONNECT LINK",
                                                     "CREATE DATASET", "CREATE EXTERNAL DATASET", "DROP DATASET", "CREATE INDEX",
                                                     "DROP INDEX", "CREATE ANALYTICS COLLECTION", "DROP ANALYTICS COLLECTION",
                                                     "CREATE ANALYTICS SCOPE", "DROP ANALYTICS SCOPE", "ALTER COLLECTION",
                                                     "CREATE ANALYTICS VIEW", "DROP ANALYTICS VIEW", "DROP LINK",
                                                     "CREATE OR REPLACE ANALYTICS VIEW"];

  cwConstantsService.healthCheckURL = "../_p/cbas/admin/ping";

  // should we show the query options button?
  cwConstantsService.showOptions = true;

  // default max warnings returned by user queries
  cwConstantsService.maxWarnings = 10;

  // default max bytes for the response until the user gets the "too big" error
  cwConstantsService.maxAceSize = 10485760;

  // default max bytes for the in progress response until the user gets the "too big for UI" error
  cwConstantsService.maxSizeForUI = 262144000; // 250MB

  // external collection constants start
  cwConstantsService.externalCollectionTypes = ['s3', 'azureblob', 'azuredatalake', 'gcs'];
  cwConstantsService.supportedExternalCollectionFormats = ['json', 'csv', 'tsv'];
  cwConstantsService.linkTypesSupportingParquet = ['s3', 'azureblob', 'azuredatalake'];

  // types that required developer preview, once all types are GAed, this field can be removed
  cwConstantsService.linkTypeParquetRequiresDeveloperPreview = ['azureblob', 'azuredatalake'];

  cwConstantsService.isExternalCollection = function (type) {
    return cwConstantsService.externalCollectionTypes.includes(type)
  };

  cwConstantsService.requireTypeDefinition = function (format) {
    return ['csv', 'tsv'].includes(format);
  };

  cwConstantsService.isParquetSupported = function (linkType) {
    return cwConstantsService.linkTypesSupportingParquet.includes(linkType);
  };

  // types that required developer preview, once all types are GAed, this function can be removed
  cwConstantsService.isParquetRequiresDeveloperPreview = function (linkType) {
    return cwConstantsService.linkTypeParquetRequiresDeveloperPreview.includes(linkType);
  };
  // external collection constants end

  //
  //
  // all done creating the service, now return it
  //

  return cwConstantsService;
}
